services:
  core:
    profiles: ["docker-core"]
    build:
      context: ..
      dockerfile: docker/Dockerfile.core
    container_name: maehbot-core
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/lib/maehbot:/var/lib/maehbot
      - ../config:/app/config:ro
    devices:
      - /dev/video0:/dev/video0
      - /dev/gpiochip0:/dev/gpiochip0
    environment:
      - MAEHBOT_CONFIG_DIR=/app/config

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    container_name: maehbot-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/maehbot:/var/lib/maehbot
      - ../config:/app/config

